version: '2'

services:
    web:
        build:
            context: ./images/confluence
            args:
                - CONFLUENCE_VERSION=${CONFLUENCE_VERSION}
                - JAVA_VERSION=8
                - JAVA_UPDATE=191
                - JAVA_BUILD=12
                - JAVA_SIG=2787e4a523244c269598db4e85c51e0c
        image: ianharrier/confluence:${CONFLUENCE_VERSION}
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - ${WEB_PORT}:8090
        environment:
            - PROXY_HOSTNAME=${WEB_PROXY_HOSTNAME}
            - PROXY_PORT=${WEB_PROXY_PORT}
            - PROXY_SCHEME=${WEB_PROXY_SCHEME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/web/data:/var/atlassian/application-data/confluence:z
    db:
        image: postgres:9.6-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        volumes:
            - ./volumes/db/data:/var/lib/postgresql/data:z
    cron:
        build:
            context: ./images/cron
        image: ianharrier/confluence-cron:1.1.1
        restart: unless-stopped
        environment:
            - BACKUP_OPERATION=${BACKUP_OPERATION}
            - BACKUP_CRON_EXP=${BACKUP_CRON_EXP}
            - BACKUP_RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - TIMEZONE=${TIMEZONE}
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        volumes:
            - ./:${PWD}:z
